/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import BO.ChoferesBo;
import JB.Choferes;
import java.awt.Image;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cardozo Villon
 */
public class ActualizarChoferes extends javax.swing.JFrame {

    /**
     * Creates new form IngresoCarreras
     */
    public ActualizarChoferes() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/IMAGENES/icono.png")).getImage());
        setTitle("MODIFICAR CHOFERES");
        btnModificar.setEnabled(false);
        
        ImageIcon fastcar = new ImageIcon(getClass().getResource("/IMAGENES/fondo.jpeg"));
        ImageIcon icon = new ImageIcon(fastcar.getImage().getScaledInstance(lblfondoPanel.getWidth(), lblfondoPanel.getHeight(), Image.SCALE_DEFAULT));
        lblfondoPanel.setIcon(icon);
        
        fastcar = new ImageIcon(getClass().getResource("/IMAGENES/fondo.jpeg"));
        icon = new ImageIcon(fastcar.getImage().getScaledInstance(lblFondoFrame.getWidth(), lblFondoFrame.getHeight(), Image.SCALE_DEFAULT));
        lblFondoFrame.setIcon(icon);
        setDefaultCloseOperation(0);
        
        lblestadoActualizarC.setVisible(false);
        lblCedulaUsuario.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIngresoChoferes = new javax.swing.JLabel();
        jPanelDatosChoferes = new javax.swing.JPanel();
        lblNombres = new javax.swing.JLabel();
        txtMovil = new javax.swing.JTextField();
        lblMovil = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblModeloVehiculo = new javax.swing.JLabel();
        txtModeloVehiculo = new javax.swing.JTextField();
        lblColorVehiculo = new javax.swing.JLabel();
        txtColorVehiculo = new javax.swing.JTextField();
        lblPlacaVehiculo = new javax.swing.JLabel();
        txtPlacaVehiculo = new javax.swing.JTextField();
        jRdInactivar = new javax.swing.JRadioButton();
        lblInactivar = new javax.swing.JLabel();
        lblfondoPanel = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblIngresoChoferes1 = new javax.swing.JLabel();
        lblFondoFrame = new javax.swing.JLabel();
        lblestadoActualizarC = new javax.swing.JLabel();
        lblCedulaUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblIngresoChoferes.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        lblIngresoChoferes.setForeground(new java.awt.Color(255, 255, 255));
        lblIngresoChoferes.setText("SISTEMA FASTCAR - MODIFICAR CHOFERES");

        jPanelDatosChoferes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNombres.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres.setText("NOMBRES");

        txtMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovilActionPerformed(evt);
            }
        });
        txtMovil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMovilKeyTyped(evt);
            }
        });

        lblMovil.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        lblMovil.setForeground(new java.awt.Color(255, 255, 255));
        lblMovil.setText("MOVIL");

        txtNombres.setEditable(false);

        lblApellidos.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidos.setText("APELLIDOS");

        txtApellidos.setEditable(false);

        lblDireccion.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccion.setText("DIRECCION");

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        lblTelefono.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono.setText("TELEFONO");

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        lblModeloVehiculo.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        lblModeloVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblModeloVehiculo.setText("MODELO VEHICULO");

        lblColorVehiculo.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        lblColorVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblColorVehiculo.setText("COLOR VEHICULO");

        txtColorVehiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColorVehiculoKeyTyped(evt);
            }
        });

        lblPlacaVehiculo.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        lblPlacaVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblPlacaVehiculo.setText("PLACA VEHICULO");

        jRdInactivar.setForeground(new java.awt.Color(255, 255, 255));
        jRdInactivar.setText("SELECCIONAR");

        lblInactivar.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        lblInactivar.setForeground(new java.awt.Color(255, 255, 255));
        lblInactivar.setText("INACTIVAR");

        javax.swing.GroupLayout jPanelDatosChoferesLayout = new javax.swing.GroupLayout(jPanelDatosChoferes);
        jPanelDatosChoferes.setLayout(jPanelDatosChoferesLayout);
        jPanelDatosChoferesLayout.setHorizontalGroup(
            jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosChoferesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColorVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlacaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosChoferesLayout.createSequentialGroup()
                        .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPlacaVehiculo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModeloVehiculo)
                            .addComponent(txtColorVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblInactivar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRdInactivar))
                    .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNombres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMovil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblfondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE))
        );
        jPanelDatosChoferesLayout.setVerticalGroup(
            jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosChoferesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMovil, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModeloVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColorVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColorVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblInactivar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRdInactivar))
                    .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPlacaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPlacaVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
                .addGap(41, 41, 41))
            .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblfondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
        );

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblIngresoChoferes1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIngresoChoferes1.setForeground(new java.awt.Color(255, 255, 255));
        lblIngresoChoferes1.setText("DATOS CHOFERES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIngresoChoferes1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelDatosChoferes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblIngresoChoferes, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresar)
                        .addGap(213, 213, 213))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFondoFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(216, 216, 216)
                    .addComponent(lblestadoActualizarC, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(421, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(217, 217, 217)
                    .addComponent(lblCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(421, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIngresoChoferes, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIngresoChoferes1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatosChoferes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnRegresar))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFondoFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(243, 243, 243)
                    .addComponent(lblestadoActualizarC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(243, 243, 243)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(249, 249, 249)
                    .addComponent(lblCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(256, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        MenuPrincipalAdmin me = new MenuPrincipalAdmin();
        me.lblEstado.setText(lblestadoActualizarC.getText());
        me.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
            me.setLocationRelativeTo(null);
            me.show();
            this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMovilActionPerformed
        try {
            // TODO add your handling code here:
            ChoferesBo bo= new ChoferesBo();
            Vector v1 = bo.ObtenerDatosChoferes(Integer.parseInt(txtMovil.getText()));
            if(!v1.isEmpty()){
            for(int i=0;i<v1.size();i++){
                Choferes ch = (Choferes)v1.get(i);
                txtNombres.setText(ch.getLV_NOMBRES());
                txtApellidos.setText(ch.getLV_APELLIDOS());
                txtDireccion.setText(ch.getLV_DIRECCION());
                txtTelefono.setText(ch.getLV_TELEFONO());
                txtModeloVehiculo.setText(ch.getLV_MODELO());
                txtColorVehiculo.setText(ch.getLV_COLOR_VEHICULO());
                txtPlacaVehiculo.setText(ch.getLV_PLACA());
                btnModificar.setEnabled(true);
            }
            }else{
                JOptionPane.showMessageDialog(null, "NO EXISTE EL MOVIL: "+txtMovil.getText(), "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
                txtMovil.setText(null);
                txtNombres.setText(null);
                txtApellidos.setText(null);
                txtDireccion.setText(null);
                txtTelefono.setText(null);
                txtModeloVehiculo.setText(null);
                txtColorVehiculo.setText(null);
                txtPlacaVehiculo.setText(null);
                btnModificar.setEnabled(false);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ActualizarChoferes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ActualizarChoferes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtMovilActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            if((txtMovil.getText().isEmpty() && txtDireccion.getText().isEmpty() && txtTelefono.getText().isEmpty() && txtModeloVehiculo.getText().isEmpty() && txtColorVehiculo.getText().isEmpty() && txtPlacaVehiculo.getText().isEmpty())||(txtMovil.getText().equals("") && txtDireccion.getText().equals("") && txtTelefono.getText().equals("") && txtModeloVehiculo.getText().equals("") && txtColorVehiculo.getText().equals("") && txtPlacaVehiculo.getText().equals(""))){
                    JOptionPane.showMessageDialog(null, "TODOS LOS CAMPOS SON OBLIGATORIOS", "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
            }else if(jRdInactivar.isSelected()){
                    int actualizarDatosChoferes=0;
                    ChoferesBo cho = new ChoferesBo();
                    actualizarDatosChoferes=cho.InactivarChofer(Integer.parseInt(txtMovil.getText()));
                    if(actualizarDatosChoferes>0){
                        JOptionPane.showMessageDialog(rootPane,"SE INACTIVO CORRECTAMENTE EL MOVIL "+txtMovil.getText());
                        txtMovil.setText(null);
                        txtNombres.setText(null);
                        txtApellidos.setText(null);
                        txtDireccion.setText(null);
                        txtTelefono.setText(null);
                        txtModeloVehiculo.setText(null);
                        txtColorVehiculo.setText(null);
                        txtPlacaVehiculo.setText(null);
                        btnModificar.setEnabled(false);
                    }
            }else{
                int actualizarDatosChoferes=0;
                    ChoferesBo cho = new ChoferesBo();
                    Choferes actu= new Choferes(null,"","",txtDireccion.getText(),txtTelefono.getText(),txtColorVehiculo.getText(),txtPlacaVehiculo.getText(),txtModeloVehiculo.getText());
                    actualizarDatosChoferes=cho.ActualizarDatosChoferes(actu,Integer.parseInt(txtMovil.getText()));
                    if(actualizarDatosChoferes>0){
                        JOptionPane.showMessageDialog(rootPane,"SE ACTUALIZARON LOS DATOS CORRECTAMENTE");
                        txtMovil.setText(null);
                        txtNombres.setText(null);
                        txtApellidos.setText(null);
                        txtDireccion.setText(null);
                        txtTelefono.setText(null);
                        txtModeloVehiculo.setText(null);
                        txtColorVehiculo.setText(null);
                        txtPlacaVehiculo.setText(null);
                        btnModificar.setEnabled(false);
                    }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ActualizarChoferes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ActualizarChoferes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtMovilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMovilKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_txtMovilKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtColorVehiculoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorVehiculoKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'a' || car>'z')&&(car<'A' || car >'Z')&& (car !=' ')) evt.consume();
    }//GEN-LAST:event_txtColorVehiculoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarChoferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarChoferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarChoferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarChoferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarChoferes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanelDatosChoferes;
    private javax.swing.JRadioButton jRdInactivar;
    private javax.swing.JLabel lblApellidos;
    public static javax.swing.JLabel lblCedulaUsuario;
    private javax.swing.JLabel lblColorVehiculo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFondoFrame;
    private javax.swing.JLabel lblInactivar;
    private javax.swing.JLabel lblIngresoChoferes;
    private javax.swing.JLabel lblIngresoChoferes1;
    private javax.swing.JLabel lblModeloVehiculo;
    private javax.swing.JLabel lblMovil;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblPlacaVehiculo;
    private javax.swing.JLabel lblTelefono;
    public static javax.swing.JLabel lblestadoActualizarC;
    private javax.swing.JLabel lblfondoPanel;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtColorVehiculo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtModeloVehiculo;
    private javax.swing.JTextField txtMovil;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPlacaVehiculo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
