/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import BO.CarrerasBo;
import BO.ChoferesBo;
import BO.PagosDiariosBo;
import proyecto_fastcar.PDFCarreras;
import JB.Carreras;
import JB.Choferes;
import com.itextpdf.text.BadElementException;
import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import proyecto_fastcar.PDFCarrerasFechas;
import proyecto_fastcar.PDFCarrerasMovil;

/**
 *
 * @author jcardozo
 */
public class ActualizarMovilReferencia extends javax.swing.JFrame {

    /**
     * Creates new form ReporteCarrerasPDF
     */
    public ActualizarMovilReferencia() {
        initComponents();
        lblTelefono.setVisible(false);
        lblfechahora.setVisible(false);
        lblDestino.setVisible(false);
        lblNumeroSorteo.setVisible(false);
        lblOrigen.setVisible(false);
        lblMovil.setVisible(false);
        lblValor.setVisible(false);
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/IMAGENES/icono.png")).getImage());
        setTitle("REPORTES CARRERAS");
        setDefaultCloseOperation(0);
        ImageIcon fastcar = new ImageIcon(getClass().getResource("/IMAGENES/fondo.jpeg"));
        ImageIcon icon = new ImageIcon(fastcar.getImage().getScaledInstance(lblfondoPanel.getWidth(), lblfondoPanel.getHeight(), Image.SCALE_DEFAULT));
        lblfondoPanel.setIcon(icon);
        
        fastcar = new ImageIcon(getClass().getResource("/IMAGENES/fondo.jpeg"));
        icon = new ImageIcon(fastcar.getImage().getScaledInstance(lblFondoFrame.getWidth(), lblFondoFrame.getHeight(), Image.SCALE_DEFAULT));
        lblFondoFrame.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupfiltro = new javax.swing.ButtonGroup();
        lblReporteCarreras = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbReferencia = new javax.swing.JLabel();
        txtReferencia = new javax.swing.JTextField();
        btnPDF = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblfechahora = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        origen = new javax.swing.JLabel();
        movil = new javax.swing.JLabel();
        destino = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblNumeroSorteo = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        txtTelefono = new javax.swing.JTextField();
        txtOrigen = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        txtMovil = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        lblOrigen = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        lblMovil = new javax.swing.JLabel();
        lblfondoPanel = new javax.swing.JLabel();
        lblValor1 = new javax.swing.JLabel();
        txtValoor = new javax.swing.JTextField();
        lblFondoFrame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblReporteCarreras.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblReporteCarreras.setForeground(new java.awt.Color(255, 255, 255));
        lblReporteCarreras.setText("SISTEMA FASTCAR - ACTUALIZACION");

        lbReferencia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbReferencia.setForeground(new java.awt.Color(255, 255, 255));
        lbReferencia.setText("REFERENCIA");

        txtReferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReferenciaKeyTyped(evt);
            }
        });

        btnPDF.setText("ACTUALIZAR");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        btnRegresar.setText("CANCELAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblfechahora.setForeground(new java.awt.Color(255, 255, 255));

        telefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        telefono.setForeground(new java.awt.Color(255, 255, 255));
        telefono.setText("TELEFONO");

        origen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        origen.setForeground(new java.awt.Color(255, 255, 255));
        origen.setText("ORIGEN");

        movil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        movil.setForeground(new java.awt.Color(255, 255, 255));
        movil.setText("MOVIL");

        destino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        destino.setForeground(new java.awt.Color(255, 255, 255));
        destino.setText("DESTINO");

        btnImprimir.setText("IMPRIMIR");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        txtMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovilActionPerformed(evt);
            }
        });

        lblValor1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValor1.setForeground(new java.awt.Color(255, 255, 255));
        lblValor1.setText("VALOR");

        txtValoor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValoorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(movil, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(origen, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDestino)
                                .addComponent(txtMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValoor, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrigen))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMovil)
                .addGap(86, 86, 86))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 300, Short.MAX_VALUE)
                    .addComponent(lblfechahora)
                    .addGap(0, 301, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 300, Short.MAX_VALUE)
                    .addComponent(lblCliente)
                    .addGap(0, 301, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 300, Short.MAX_VALUE)
                    .addComponent(lblValor)
                    .addGap(0, 301, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 300, Short.MAX_VALUE)
                    .addComponent(lblNumeroSorteo)
                    .addGap(0, 301, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(304, 304, 304)
                    .addComponent(lblDestino)
                    .addContainerGap(331, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblfondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOrigen)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMovil)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(origen, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(movil, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValoor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir)
                    .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 124, Short.MAX_VALUE)
                    .addComponent(lblfechahora)
                    .addGap(0, 124, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 124, Short.MAX_VALUE)
                    .addComponent(lblCliente)
                    .addGap(0, 124, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 124, Short.MAX_VALUE)
                    .addComponent(lblValor)
                    .addGap(0, 124, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 124, Short.MAX_VALUE)
                    .addComponent(lblNumeroSorteo)
                    .addGap(0, 124, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(154, 154, 154)
                    .addComponent(lblDestino)
                    .addContainerGap(108, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblfondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(lblReporteCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFondoFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReporteCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFondoFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        try {
            // TODO add your handling code here:
            int n=0;
            int movil=Integer.parseInt(txtMovil.getText());
            int pagoDiario=0;
            String estado=null;
            ChoferesBo bo2 = new ChoferesBo();
            n=bo2.ValidarChoferesRegistrados(movil);
            if(n==0){
                JOptionPane.showMessageDialog(null, "NO SE ENCUENTRA REGISTRADO EL MOVIL "+movil, "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
            }else{
                estado=bo2.EstadoMovil(movil);
                PagosDiariosBo pbo = new PagosDiariosBo();
                pagoDiario=pbo.ValidarPagoChofer(movil);
                if(pagoDiario>0 || Integer.parseInt(txtMovil.getText()) == 20 || Integer.parseInt(txtMovil.getText()) == 37 || estado.equals("A")|| txtMovil.getText().equals(lblMovil.getText())){
                    
                    try {
                        CarrerasBo bo = new CarrerasBo();
                        int obtener = bo.ActualizarReferencia(txtReferencia.getText(),Float.parseFloat(txtValoor.getText()), txtTelefono.getText(),txtOrigen.getText(),txtDestino.getText(),Integer.parseInt(txtMovil.getText()),lblTelefono.getText(),lblOrigen.getText(),lblDestino.getText(),Integer.parseInt(lblMovil.getText()),lblfechahora.getText());
                        if(obtener ==1){
                            JOptionPane.showMessageDialog(rootPane,"SE ACTUALIZO CORRECTAMENTE");
                            HistorialCarreras frm = new HistorialCarreras();
                            frm.show();
                            frm.setExtendedState(MAXIMIZED_BOTH);
                            this.dispose();
                        }
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(ActualizarMovilReferencia.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(ActualizarMovilReferencia.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "NO SE PUEDE ASIGNAR EL MOVIL "+movil+" , DEBIDO QUE ESTA ATRASADO CON SU PAGO", "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ActualizarMovilReferencia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ActualizarMovilReferencia.class.getName()).log(Level.SEVERE, null, ex);
        }
              
              
    }//GEN-LAST:event_btnPDFActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        HistorialCarreras frm = new HistorialCarreras();
                          frm.show();
                          frm.setExtendedState(MAXIMIZED_BOTH);
            this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtReferenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReferenciaKeyTyped

    }//GEN-LAST:event_txtReferenciaKeyTyped

    
    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        try {
            // TODO add your handling code here:
            int n=0;
            int movil=Integer.parseInt(txtMovil.getText());
            int pagoDiario=0;
            String estado=null;
            ChoferesBo bo2 = new ChoferesBo();
            n=bo2.ValidarChoferesRegistrados(movil);
            if(n==0){
                JOptionPane.showMessageDialog(null, "NO SE ENCUENTRA REGISTRADO EL MOVIL "+movil, "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
            }else{
                estado=bo2.EstadoMovil(movil);
                PagosDiariosBo pbo = new PagosDiariosBo();
                pagoDiario=pbo.ValidarPagoChofer(movil);
                if(pagoDiario>0 || Integer.parseInt(txtMovil.getText()) == 20 || Integer.parseInt(txtMovil.getText()) == 37 || estado.equals("A")|| txtMovil.getText().equals(lblMovil.getText())){
                    if(lblNumeroSorteo.getText() == null){
                        try {
                            CarrerasBo bo = new CarrerasBo();
                            System.out.print(txtTelefono.getText()+ " "+txtOrigen.getText()+ " "+txtDestino.getText()+ " "+lblfechahora.getText());
                            String NombreCliente = bo.ObtenerNombrecliente(txtTelefono.getText(), txtOrigen.getText(), txtDestino.getText(), lblfechahora.getText());
                            ImpresionCarrera frm = new ImpresionCarrera();
                            frm.txtCliente.setText(NombreCliente);
                            frm.txtTelefono.setText(txtTelefono.getText());
                            frm.txtDireccion.setText(txtOrigen.getText());
                            frm.txtRefrencia.setText(txtReferencia.getText());
                            frm.txtDestino.setText(txtDestino.getText());
                            frm.txtValor.setText(lblValor.getText());
                            frm.txtMovil.setText(txtMovil.getText());
                            frm.txtFecha.setText(lblfechahora.getText());
                            frm.lblBandera.setText("H");
                            frm.show();
                            this.dispose();
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(ActualizarMovilReferencia.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (SQLException ex) {
                            Logger.getLogger(ActualizarMovilReferencia.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }else{
                        try {
                            ImpresionCarreraPromociones frm = new ImpresionCarreraPromociones();
                            CarrerasBo bo = new CarrerasBo();
                            String NombreCliente = bo.ObtenerNombrecliente(txtTelefono.getText(), txtOrigen.getText(), txtDestino.getText(), lblfechahora.getText());
                            frm.txtCliente.setText(NombreCliente);
                            frm.txtTelefono.setText(txtTelefono.getText());
                            frm.txtDireccion.setText(txtOrigen.getText());
                            frm.txtRefrencia.setText(txtReferencia.getText());
                            frm.txtDestino.setText(txtDestino.getText());
                            frm.txtValor.setText(lblValor.getText());
                            frm.txtMovil.setText(txtMovil.getText());
                            frm.txtFecha.setText(lblfechahora.getText());
                            frm.txtNumero.setText(lblNumeroSorteo.getText());
                            frm.lblBandera.setText("H");
                            frm.show();
                            this.dispose();
                        } catch (SQLException ex) {
                            Logger.getLogger(ActualizarMovilReferencia.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(ActualizarMovilReferencia.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "NO SE PUEDE ASIGNAR EL MOVIL "+movil+" , DEBIDO QUE ESTA ATRASADO CON SU PAGO", "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ActualizarMovilReferencia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ActualizarMovilReferencia.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
                
            
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void txtValoorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValoorKeyTyped
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')&&(car!='.')) evt.consume();
    }//GEN-LAST:event_txtValoorKeyTyped

    private void txtMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMovilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMovilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarMovilReferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarMovilReferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarMovilReferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarMovilReferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarMovilReferencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnRegresar;
    private javax.swing.ButtonGroup buttonGroupfiltro;
    private javax.swing.JLabel destino;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbReferencia;
    public static javax.swing.JLabel lblCliente;
    public static javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblFondoFrame;
    public static javax.swing.JLabel lblMovil;
    public static javax.swing.JLabel lblNumeroSorteo;
    public static javax.swing.JLabel lblOrigen;
    private javax.swing.JLabel lblReporteCarreras;
    public static javax.swing.JLabel lblTelefono;
    public static javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValor1;
    public static javax.swing.JLabel lblfechahora;
    private javax.swing.JLabel lblfondoPanel;
    private javax.swing.JLabel movil;
    private javax.swing.JLabel origen;
    private javax.swing.JLabel telefono;
    public static javax.swing.JTextField txtDestino;
    public static javax.swing.JTextField txtMovil;
    public static javax.swing.JTextField txtOrigen;
    public static javax.swing.JTextField txtReferencia;
    public static javax.swing.JTextField txtTelefono;
    public static javax.swing.JTextField txtValoor;
    // End of variables declaration//GEN-END:variables
}
