/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import BO.ChoferesBo;
import JB.Choferes;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cardozo Villon
 */
public class IngresoChoferes extends javax.swing.JFrame {

    /**
     * Creates new form IngresoCarreras
     */
    public IngresoChoferes() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/IMAGENES/icono.png")).getImage());
        setTitle("INGRESO CHOFERES");
        setDefaultCloseOperation(0);
        ImageIcon fastcar = new ImageIcon(getClass().getResource("/IMAGENES/fondo.jpeg"));
        ImageIcon icon = new ImageIcon(fastcar.getImage().getScaledInstance(lblfondoPanel.getWidth(), lblfondoPanel.getHeight(), Image.SCALE_DEFAULT));
        lblfondoPanel.setIcon(icon);
        lblEstadoIngresoC.setVisible(false);
        lblCedulaUsuario.setVisible(false);
        Apoyo.setSelected(true);
        fastcar = new ImageIcon(getClass().getResource("/IMAGENES/fondo.jpeg"));
        icon = new ImageIcon(fastcar.getImage().getScaledInstance(lblFondoFrame.getWidth(), lblFondoFrame.getHeight(), Image.SCALE_DEFAULT));
        lblFondoFrame.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblIngresoChoferes = new javax.swing.JLabel();
        jPanelDatosChoferes = new javax.swing.JPanel();
        lblNombres = new javax.swing.JLabel();
        txtMovil = new javax.swing.JTextField();
        lblMovil = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblModeloVehiculo = new javax.swing.JLabel();
        txtModeloVehiculo = new javax.swing.JTextField();
        lblColorVehiculo = new javax.swing.JLabel();
        txtColorVehiculo = new javax.swing.JTextField();
        lblPlacaVehiculo = new javax.swing.JLabel();
        txtPlacaVehiculo = new javax.swing.JTextField();
        lblTipoMovil = new javax.swing.JLabel();
        Apoyo = new javax.swing.JRadioButton();
        Fijo = new javax.swing.JRadioButton();
        lblfondoPanel = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblIngresoChoferes1 = new javax.swing.JLabel();
        lblEstadoIngresoC = new javax.swing.JLabel();
        lblCedulaUsuario = new javax.swing.JLabel();
        lblFondoFrame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblIngresoChoferes.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblIngresoChoferes.setForeground(new java.awt.Color(255, 255, 255));
        lblIngresoChoferes.setText("SISTEMA FASTCAR - INGRESO CHOFERES");

        jPanelDatosChoferes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNombres.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres.setText("NOMBRES");

        txtMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovilActionPerformed(evt);
            }
        });
        txtMovil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMovilKeyTyped(evt);
            }
        });

        lblMovil.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblMovil.setForeground(new java.awt.Color(255, 255, 255));
        lblMovil.setText("MOVIL");

        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });

        lblApellidos.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidos.setText("APELLIDOS");

        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });

        lblDireccion.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccion.setText("DIRECCION");

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        lblTelefono.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono.setText("TELEFONO");

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        lblModeloVehiculo.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblModeloVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblModeloVehiculo.setText("MODELO VEHICULO");

        lblColorVehiculo.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblColorVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblColorVehiculo.setText("COLOR VEHICULO");

        txtColorVehiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColorVehiculoKeyTyped(evt);
            }
        });

        lblPlacaVehiculo.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblPlacaVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblPlacaVehiculo.setText("PLACA VEHICULO");

        lblTipoMovil.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblTipoMovil.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoMovil.setText("TIPO MOVIL");

        buttonGroup1.add(Apoyo);
        Apoyo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Apoyo.setForeground(new java.awt.Color(255, 255, 255));
        Apoyo.setText("APOYO");

        buttonGroup1.add(Fijo);
        Fijo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Fijo.setForeground(new java.awt.Color(255, 255, 255));
        Fijo.setText("FIJO");

        javax.swing.GroupLayout jPanelDatosChoferesLayout = new javax.swing.GroupLayout(jPanelDatosChoferes);
        jPanelDatosChoferes.setLayout(jPanelDatosChoferesLayout);
        jPanelDatosChoferesLayout.setHorizontalGroup(
            jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosChoferesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosChoferesLayout.createSequentialGroup()
                        .addComponent(lblTipoMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Apoyo)
                        .addGap(27, 27, 27)
                        .addComponent(Fijo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelDatosChoferesLayout.createSequentialGroup()
                        .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosChoferesLayout.createSequentialGroup()
                                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(lblDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelDatosChoferesLayout.createSequentialGroup()
                                .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatosChoferesLayout.createSequentialGroup()
                                    .addComponent(lblModeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtModeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatosChoferesLayout.createSequentialGroup()
                                    .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblPlacaVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblColorVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(38, 38, 38)
                                    .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelDatosChoferesLayout.createSequentialGroup()
                                            .addComponent(txtPlacaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(txtColorVehiculo)))))
                        .addContainerGap(156, Short.MAX_VALUE))))
            .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblfondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE))
        );
        jPanelDatosChoferesLayout.setVerticalGroup(
            jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosChoferesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMovil, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModeloVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColorVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColorVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlacaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlacaVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apoyo)
                    .addComponent(Fijo))
                .addGap(17, 17, 17))
            .addGroup(jPanelDatosChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblfondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
        );

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblIngresoChoferes1.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblIngresoChoferes1.setForeground(new java.awt.Color(255, 255, 255));
        lblIngresoChoferes1.setText("DATOS CHOFER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(lblIngresoChoferes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIngresoChoferes1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelDatosChoferes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnRegistrar)
                        .addGap(39, 39, 39)
                        .addComponent(btnRegresar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(194, 194, 194)
                    .addComponent(lblEstadoIngresoC, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(367, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(195, 195, 195)
                    .addComponent(lblCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(367, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFondoFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIngresoChoferes, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIngresoChoferes1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDatosChoferes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnRegresar))
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(230, 230, 230)
                    .addComponent(lblEstadoIngresoC, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addGap(231, 231, 231)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(236, 236, 236)
                    .addComponent(lblCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(318, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFondoFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        if(lblEstadoIngresoC.getText().equals("A")){
            MenuPrincipalAdmin me = new MenuPrincipalAdmin();
            me.lblEstado.setText(lblEstadoIngresoC.getText());
            me.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
            me.setLocationRelativeTo(null);
            me.show();
            this.dispose();
        }else if (lblEstadoIngresoC.getText().equals("C")) {
            MenuPrincipalConsulta me = new MenuPrincipalConsulta();
            me.lblEstado.setText(lblEstadoIngresoC.getText());
            me.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
            me.setLocationRelativeTo(null);
            me.show();
            this.dispose();
        }else if (lblEstadoIngresoC.getText().equals("O")) {
            MenuPrincipalOperadoras me = new MenuPrincipalOperadoras();
            me.lblEstado.setText(lblEstadoIngresoC.getText());
            me.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
            me.setLocationRelativeTo(null);
            me.show();
            this.dispose();
        }
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //Validar que los campos son boligatorios
        if(txtMovil.getText().isEmpty() || txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty() || txtDireccion.getText().isEmpty() || txtTelefono.getText().isEmpty() || txtModeloVehiculo.getText().isEmpty() || txtColorVehiculo.getText().isEmpty() || txtPlacaVehiculo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "TODOS LOS CAMPOS SON OBLIGATORIOS", "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                int n=0;
                int ingresoChoferes=0;
                int movil=Integer.parseInt(txtMovil.getText());
                String estado= null;
                ChoferesBo bo = new ChoferesBo();
                n=bo.ValidarChoferesRegistrados(movil);
                if(n==0){
                    ChoferesBo BO = new ChoferesBo();
                    if(Apoyo.isSelected()){
                        estado = "A";
                    }else if (Fijo.isSelected()){
                        estado = "F";
                    }
                    
                    Choferes in= new Choferes(movil,txtNombres.getText(), txtApellidos.getText(), txtDireccion.getText(), txtTelefono.getText(),txtColorVehiculo.getText(),txtPlacaVehiculo.getText(), txtModeloVehiculo.getText());
                    ingresoChoferes=BO.RegistrarChoferNuevo(in,estado);
                    if(ingresoChoferes>0){
                        JOptionPane.showMessageDialog(rootPane,"CHOFER INGRESADO CORRECTAMENTE");
                        txtMovil.setText(null);
                        txtNombres.setText(null);
                        txtApellidos.setText(null);
                        txtDireccion.setText(null); 
                        txtTelefono.setText(null); 
                        txtModeloVehiculo.setText(null);
                        txtColorVehiculo.setText(null);
                        txtPlacaVehiculo.setText(null);
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "EL MOVIL: "+movil+" YA SE ENCUENTRA REGISTRADO", "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(IngresoChoferes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(IngresoChoferes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtMovilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMovilKeyTyped
       char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_txtMovilKeyTyped

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        char car = evt.getKeyChar();
        if((car<'a' || car>'z')&&(car<'A' || car >'Z')&& (car !=' ')) evt.consume(); 
    }//GEN-LAST:event_txtNombresKeyTyped

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
        char car = evt.getKeyChar();
        if((car<'a' || car>'z')&&(car<'A' || car >'Z')&& (car !=' ')) evt.consume();
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMovilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMovilActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtColorVehiculoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorVehiculoKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'a' || car>'z')&&(car<'A' || car >'Z')&& (car !=' ')) evt.consume();
    }//GEN-LAST:event_txtColorVehiculoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoChoferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoChoferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoChoferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoChoferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoChoferes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Apoyo;
    private javax.swing.JRadioButton Fijo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanelDatosChoferes;
    private javax.swing.JLabel lblApellidos;
    public static javax.swing.JLabel lblCedulaUsuario;
    private javax.swing.JLabel lblColorVehiculo;
    private javax.swing.JLabel lblDireccion;
    public static javax.swing.JLabel lblEstadoIngresoC;
    private javax.swing.JLabel lblFondoFrame;
    private javax.swing.JLabel lblIngresoChoferes;
    private javax.swing.JLabel lblIngresoChoferes1;
    private javax.swing.JLabel lblModeloVehiculo;
    private javax.swing.JLabel lblMovil;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblPlacaVehiculo;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipoMovil;
    private javax.swing.JLabel lblfondoPanel;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtColorVehiculo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtModeloVehiculo;
    private javax.swing.JTextField txtMovil;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPlacaVehiculo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
