/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import BO.PromocionesBo;
import BO.RegalosBo;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import proyecto_fastcar.Control;

/**
 *
 * @author Cardozo Villon
 */
public class MenuPrincipalAdmin extends javax.swing.JFrame implements ActionListener{
Timer timer = new Timer(1000, (ActionListener) this);
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipalAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/IMAGENES/icono.png")).getImage());
        setTitle("MENU PRINCIPAL USUARIO ADMINISTRADOR");
        lblEstado.setVisible(false);
        lblCedulaUsuario.setVisible(false);
        timer.start();
        ImageIcon fastcar = new ImageIcon(getClass().getResource("/IMAGENES/logo.png"));
        ImageIcon icon = new ImageIcon(fastcar.getImage().getScaledInstance(lblimagen.getWidth(), lblimagen.getHeight(), Image.SCALE_DEFAULT));
        lblimagen.setIcon(icon);
        
        fastcar = new ImageIcon(getClass().getResource("/IMAGENES/fondo.jpeg"));
        icon = new ImageIcon(fastcar.getImage().getScaledInstance(lblFondoFrame.getWidth(), lblFondoFrame.getHeight(), Image.SCALE_DEFAULT));
        lblFondoFrame.setIcon(icon);
        
        setDefaultCloseOperation(0);
    }
    
    public void actionPerformed(ActionEvent e) {
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");         
        lblClock.setText(sdf.format(new java.util.Date()));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenuPrincipal = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        lblimagen = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblFondoFrame = new javax.swing.JLabel();
        lblCedulaUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JmenuCarreras = new javax.swing.JMenu();
        JmenuIngresoCarreras = new javax.swing.JMenuItem();
        JmenuRegistroValores = new javax.swing.JMenuItem();
        jmenuPromociones = new javax.swing.JMenu();
        jMenuIniciarPromocion = new javax.swing.JMenuItem();
        jMenuFinalizarPromocion = new javax.swing.JMenuItem();
        jMenuReporteCarreras = new javax.swing.JMenuItem();
        jmenuRegalos = new javax.swing.JMenu();
        jMenuIniciarRegalos = new javax.swing.JMenuItem();
        jMenuFinalizarRegalos = new javax.swing.JMenuItem();
        JMenuChoferes = new javax.swing.JMenu();
        JmenuRegistroChoferes = new javax.swing.JMenuItem();
        JmenuModificarChofer = new javax.swing.JMenuItem();
        JmenuPagosDiarios = new javax.swing.JMenuItem();
        jMenuReportesChoferes = new javax.swing.JMenuItem();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuIngresarUsuario = new javax.swing.JMenuItem();
        jMenuModificarUsuario = new javax.swing.JMenuItem();
        jMenuHistorialCarrera = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblMenuPrincipal.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        lblMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuPrincipal.setText("SISTEMA FASTCAR - MENU PRINCIPAL ADMINISTRADOR");

        lblClock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        JmenuCarreras.setText("CARRERAS");
        JmenuCarreras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        JmenuIngresoCarreras.setText("INGRESO");
        JmenuIngresoCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmenuIngresoCarrerasActionPerformed(evt);
            }
        });
        JmenuCarreras.add(JmenuIngresoCarreras);

        JmenuRegistroValores.setText("REGISTRO VALORES");
        JmenuRegistroValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmenuRegistroValoresActionPerformed(evt);
            }
        });
        JmenuCarreras.add(JmenuRegistroValores);

        jmenuPromociones.setText("PROMOCIONES");

        jMenuIniciarPromocion.setText("INICIAR PROMOCION");
        jMenuIniciarPromocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIniciarPromocionActionPerformed(evt);
            }
        });
        jmenuPromociones.add(jMenuIniciarPromocion);

        jMenuFinalizarPromocion.setText("FINALIZAR PROMOCION");
        jMenuFinalizarPromocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFinalizarPromocionActionPerformed(evt);
            }
        });
        jmenuPromociones.add(jMenuFinalizarPromocion);

        JmenuCarreras.add(jmenuPromociones);

        jMenuReporteCarreras.setText("REPORTES");
        jMenuReporteCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReporteCarrerasActionPerformed(evt);
            }
        });
        JmenuCarreras.add(jMenuReporteCarreras);

        jmenuRegalos.setText("REGALOS");

        jMenuIniciarRegalos.setText("INICIAR REGALOS");
        jMenuIniciarRegalos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIniciarRegalosActionPerformed(evt);
            }
        });
        jmenuRegalos.add(jMenuIniciarRegalos);

        jMenuFinalizarRegalos.setText("FINALIZAR REGALOS");
        jMenuFinalizarRegalos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFinalizarRegalosActionPerformed(evt);
            }
        });
        jmenuRegalos.add(jMenuFinalizarRegalos);

        JmenuCarreras.add(jmenuRegalos);

        jMenuBar1.add(JmenuCarreras);

        JMenuChoferes.setText("CHOFERES");
        JMenuChoferes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        JmenuRegistroChoferes.setText("REGISTRO");
        JmenuRegistroChoferes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmenuRegistroChoferesActionPerformed(evt);
            }
        });
        JMenuChoferes.add(JmenuRegistroChoferes);

        JmenuModificarChofer.setText("MODIFICAR");
        JmenuModificarChofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmenuModificarChoferActionPerformed(evt);
            }
        });
        JMenuChoferes.add(JmenuModificarChofer);

        JmenuPagosDiarios.setText("PAGOS DIARIOS");
        JmenuPagosDiarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmenuPagosDiariosActionPerformed(evt);
            }
        });
        JMenuChoferes.add(JmenuPagosDiarios);

        jMenuReportesChoferes.setText("REPORTES");
        jMenuReportesChoferes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReportesChoferesActionPerformed(evt);
            }
        });
        JMenuChoferes.add(jMenuReportesChoferes);

        jMenuBar1.add(JMenuChoferes);

        jMenuUsuarios.setText("USUARIOS");
        jMenuUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuIngresarUsuario.setText("INGRESO");
        jMenuIngresarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIngresarUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuIngresarUsuario);

        jMenuModificarUsuario.setText("MODIFICAR");
        jMenuModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificarUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuModificarUsuario);

        jMenuBar1.add(jMenuUsuarios);

        jMenuHistorialCarrera.setText("HISTORIAL CARRERA");
        jMenuHistorialCarrera.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuHistorialCarrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuHistorialCarreraMousePressed(evt);
            }
        });
        jMenuHistorialCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHistorialCarreraActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuHistorialCarrera);

        jMenuSalir.setText("SALIR");
        jMenuSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuSalirMousePressed(evt);
            }
        });
        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFondoFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(lblCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(769, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(lblMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFondoFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(lblCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(340, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void JmenuIngresoCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmenuIngresoCarrerasActionPerformed
        // TODO add your handling code here:

        IngresoCarreras frm = new IngresoCarreras();
        frm.lblEstadoCarrera.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
        //this.dispose();
    }//GEN-LAST:event_JmenuIngresoCarrerasActionPerformed

    private void JmenuRegistroChoferesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmenuRegistroChoferesActionPerformed
        // TODO add your handling code here:
        IngresoChoferes frm = new IngresoChoferes();
        frm.lblEstadoIngresoC.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
        this.dispose();
    }//GEN-LAST:event_JmenuRegistroChoferesActionPerformed

    private void JmenuModificarChoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmenuModificarChoferActionPerformed
        // TODO add your handling code here:
        ActualizarChoferes frm = new ActualizarChoferes();
        frm.lblestadoActualizarC.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
        this.dispose();
    }//GEN-LAST:event_JmenuModificarChoferActionPerformed

    private void JmenuPagosDiariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmenuPagosDiariosActionPerformed
        // TODO add your handling code here:
        PagosDiariosChoferes frm = new PagosDiariosChoferes();
        frm.lblestadoPagos.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
        this.dispose();
    }//GEN-LAST:event_JmenuPagosDiariosActionPerformed

    private void JmenuRegistroValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmenuRegistroValoresActionPerformed
        // TODO add your handling code here:
        RegistroValores frm = new RegistroValores();
        frm.lblEstadoValores.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
        this.dispose();
    }//GEN-LAST:event_JmenuRegistroValoresActionPerformed

    private void jMenuIngresarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIngresarUsuarioActionPerformed
        // TODO add your handling code here:
        IngresoUsuarios frm = new IngresoUsuarios();
        frm.lblEstadoIngresoU.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
        this.dispose();
    }//GEN-LAST:event_jMenuIngresarUsuarioActionPerformed

    private void jMenuModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificarUsuarioActionPerformed
        // TODO add your handling code here:
        ActualizarUsuarios frm = new ActualizarUsuarios();
        frm.lblEstadoActualizarU.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
        this.dispose();
    }//GEN-LAST:event_jMenuModificarUsuarioActionPerformed

    private void jMenuIniciarPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIniciarPromocionActionPerformed
        // TODO add your handling code here:
        IngresarPromociones frm = new IngresarPromociones();
        frm.lblEstadoPromociones.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
        this.dispose();
    }//GEN-LAST:event_jMenuIniciarPromocionActionPerformed

    private void jMenuFinalizarPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFinalizarPromocionActionPerformed
        // TODO add your handling code here:
        try {
                int n=0;
                int finalizarPromocion=0;
                PromocionesBo bo = new PromocionesBo();
                n=bo.ValidarPromociones();
                if(n==1){
                    int codigo=JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea finalizar la promocion?", "Alerta de Confirmacion!", JOptionPane.YES_NO_OPTION);
                        if (codigo==JOptionPane.YES_OPTION){    
                            finalizarPromocion=bo.FinalizarPromociones();
                            if(finalizarPromocion>0){
                                JOptionPane.showMessageDialog(rootPane,"SE FINALIZO LA PROMOCION CORRECTAMENTE");
                                
                            }
                        }else if(codigo==JOptionPane.NO_OPTION){
                            JOptionPane.showMessageDialog(rootPane,"SE HA CANCELADO LA ACCION");
                        }
                }else{
                    JOptionPane.showMessageDialog(null, "NO HAY PROMOCION REGISTRADA", "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuFinalizarPromocionActionPerformed

    private void jMenuHistorialCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHistorialCarreraActionPerformed
        
    }//GEN-LAST:event_jMenuHistorialCarreraActionPerformed

        
    private void jMenuReporteCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReporteCarrerasActionPerformed
        // TODO add your handling code here:
        ReporteCarrerasPDF frm = new ReporteCarrerasPDF();
        frm.lblEstadoReporteC.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
        this.dispose();
    }//GEN-LAST:event_jMenuReporteCarrerasActionPerformed

    private void jMenuReportesChoferesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReportesChoferesActionPerformed
        // TODO add your handling code here:
        ReporteChoferesPDF frm = new ReporteChoferesPDF();
        frm.lblReportechofer.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
        this.dispose();
    }//GEN-LAST:event_jMenuReportesChoferesActionPerformed

    private void jMenuSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalirMousePressed
        // TODO add your handling code here:
        new Control().cerrarApp();
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirMousePressed

    private void jMenuHistorialCarreraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHistorialCarreraMousePressed
        // TODO add your handling code here:
        HistorialCarreras me = new HistorialCarreras();
        me.setExtendedState(MAXIMIZED_BOTH);
        me.show();
    }//GEN-LAST:event_jMenuHistorialCarreraMousePressed

    private void jMenuIniciarRegalosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIniciarRegalosActionPerformed
        // TODO add your handling code here:
        IngresarRegalos frm = new IngresarRegalos();
        frm.lblEstadoRegalos.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
        this.dispose();
    }//GEN-LAST:event_jMenuIniciarRegalosActionPerformed

    private void jMenuFinalizarRegalosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFinalizarRegalosActionPerformed
        // TODO add your handling code here:
         try {
                int n=0;
                int finalizarRegalo=0;
                RegalosBo bo = new RegalosBo();
                n=bo.ValidarRegalos();
                if(n==1){
                    int codigo=JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea finalizar el regalo?", "Alerta de Confirmacion!", JOptionPane.YES_NO_OPTION);
                        if (codigo==JOptionPane.YES_OPTION){    
                            finalizarRegalo=bo.FinalizarRegalos();
                            if(finalizarRegalo>0){
                                JOptionPane.showMessageDialog(rootPane,"SE FINALIZO EL REGALO CORRECTAMENTE");
                                
                            }
                        }else if(codigo==JOptionPane.NO_OPTION){
                            JOptionPane.showMessageDialog(rootPane,"SE HA CANCELADO LA ACCION");
                        }
                }else{
                    JOptionPane.showMessageDialog(null, "NO HAY REGALO REGISTRADA", "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuFinalizarRegalosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuChoferes;
    private javax.swing.JMenu JmenuCarreras;
    private javax.swing.JMenuItem JmenuIngresoCarreras;
    private javax.swing.JMenuItem JmenuModificarChofer;
    private javax.swing.JMenuItem JmenuPagosDiarios;
    private javax.swing.JMenuItem JmenuRegistroChoferes;
    private javax.swing.JMenuItem JmenuRegistroValores;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuFinalizarPromocion;
    private javax.swing.JMenuItem jMenuFinalizarRegalos;
    private javax.swing.JMenu jMenuHistorialCarrera;
    private javax.swing.JMenuItem jMenuIngresarUsuario;
    private javax.swing.JMenuItem jMenuIniciarPromocion;
    private javax.swing.JMenuItem jMenuIniciarRegalos;
    private javax.swing.JMenuItem jMenuModificarUsuario;
    private javax.swing.JMenuItem jMenuReporteCarreras;
    private javax.swing.JMenuItem jMenuReportesChoferes;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JMenu jmenuPromociones;
    private javax.swing.JMenu jmenuRegalos;
    public static javax.swing.JLabel lblCedulaUsuario;
    private javax.swing.JLabel lblClock;
    public static javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFondoFrame;
    private javax.swing.JLabel lblMenuPrincipal;
    private javax.swing.JLabel lblimagen;
    // End of variables declaration//GEN-END:variables
}
