/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import BO.PromocionesBo;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import proyecto_fastcar.Control;

/**
 *
 * @author Cardozo Villon
 */
public class MenuPrincipalOperadoras extends javax.swing.JFrame implements ActionListener{
Timer timer = new Timer(1000, (ActionListener) this);
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipalOperadoras() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/IMAGENES/icono.png")).getImage());
        setTitle("MENU PRINCIPAL USUARIO OPERADOR");
        lblEstado.setVisible(false);
        lblCedulaUsuario.setVisible(false);
        timer.start();
        ImageIcon fastcar = new ImageIcon(getClass().getResource("/IMAGENES/logo.png"));
        ImageIcon icon = new ImageIcon(fastcar.getImage().getScaledInstance(lblimagen.getWidth(), lblimagen.getHeight(), Image.SCALE_DEFAULT));
        lblimagen.setIcon(icon);
        
        fastcar = new ImageIcon(getClass().getResource("/IMAGENES/fondo.jpeg"));
        icon = new ImageIcon(fastcar.getImage().getScaledInstance(lblFondoFrame.getWidth(), lblFondoFrame.getHeight(), Image.SCALE_DEFAULT));
        lblFondoFrame.setIcon(icon);
        
        //lblEstado.setVisible(false);
        setDefaultCloseOperation(0);
    }
    
    public void actionPerformed(ActionEvent e) {
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");         
        lblClock.setText(sdf.format(new java.util.Date()));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClock = new javax.swing.JLabel();
        lblimagen = new javax.swing.JLabel();
        lblFondoFrame = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblCedulaUsuario = new javax.swing.JLabel();
        lblMenuPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JmenuCarreras = new javax.swing.JMenu();
        JmenuIngresoCarreras = new javax.swing.JMenuItem();
        JmenuRegistroValores = new javax.swing.JMenuItem();
        JMenuChoferes = new javax.swing.JMenu();
        JmenuPagosDiarios = new javax.swing.JMenuItem();
        jMenuRegistro = new javax.swing.JMenuItem();
        jMenuReportesChoferes = new javax.swing.JMenuItem();
        jMenuHistorialCarrera = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblClock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblMenuPrincipal.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        lblMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuPrincipal.setText("SISTEMA FASTCAR - MENU PRINCIPAL OPERADORAS");

        JmenuCarreras.setText("CARRERAS");
        JmenuCarreras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        JmenuIngresoCarreras.setText("INGRESO");
        JmenuIngresoCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmenuIngresoCarrerasActionPerformed(evt);
            }
        });
        JmenuCarreras.add(JmenuIngresoCarreras);

        JmenuRegistroValores.setText("REGISTRO VALORES");
        JmenuRegistroValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmenuRegistroValoresActionPerformed(evt);
            }
        });
        JmenuCarreras.add(JmenuRegistroValores);

        jMenuBar1.add(JmenuCarreras);

        JMenuChoferes.setText("CHOFERES");
        JMenuChoferes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        JmenuPagosDiarios.setText("PAGOS DIARIOS");
        JmenuPagosDiarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmenuPagosDiariosActionPerformed(evt);
            }
        });
        JMenuChoferes.add(JmenuPagosDiarios);

        jMenuRegistro.setText("REGISTRO");
        jMenuRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegistroActionPerformed(evt);
            }
        });
        JMenuChoferes.add(jMenuRegistro);

        jMenuReportesChoferes.setText("REPORTES");
        jMenuReportesChoferes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReportesChoferesActionPerformed(evt);
            }
        });
        JMenuChoferes.add(jMenuReportesChoferes);

        jMenuBar1.add(JMenuChoferes);

        jMenuHistorialCarrera.setText("HISTORIAL CARRERA");
        jMenuHistorialCarrera.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuHistorialCarrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuHistorialCarreraMousePressed(evt);
            }
        });
        jMenuHistorialCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHistorialCarreraActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuHistorialCarrera);

        jMenuSalir.setText("SALIR");
        jMenuSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuSalirMousePressed(evt);
            }
        });
        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lblMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFondoFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(222, 222, 222)
                    .addComponent(lblCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(612, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(1, 1, 1)
                .addComponent(lblMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFondoFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addComponent(lblCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(166, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JmenuPagosDiariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmenuPagosDiariosActionPerformed
        // TODO add your handling code here:
        PagosDiariosChoferes frm = new PagosDiariosChoferes();
        frm.lblestadoPagos.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
        this.dispose();
    }//GEN-LAST:event_JmenuPagosDiariosActionPerformed


    private void jMenuSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalirMousePressed
        // TODO add your handling code here:
        new Control().cerrarApp();
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirMousePressed

    private void jMenuRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegistroActionPerformed
        // TODO add your handling code here:
        IngresoChoferes frm = new IngresoChoferes();
        frm.lblEstadoIngresoC.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
        this.dispose();
    }//GEN-LAST:event_jMenuRegistroActionPerformed

    private void jMenuReportesChoferesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReportesChoferesActionPerformed
        // TODO add your handling code here:
        ReporteChoferesPDF frm = new ReporteChoferesPDF();
        frm.lblReportechofer.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
        this.dispose();
    }//GEN-LAST:event_jMenuReportesChoferesActionPerformed

    private void jMenuHistorialCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHistorialCarreraActionPerformed

    }//GEN-LAST:event_jMenuHistorialCarreraActionPerformed

    private void jMenuHistorialCarreraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHistorialCarreraMousePressed
        // TODO add your handling code here:
        HistorialCarreras me = new HistorialCarreras();
        me.setExtendedState(MAXIMIZED_BOTH);
        me.show();
    }//GEN-LAST:event_jMenuHistorialCarreraMousePressed

    private void JmenuRegistroValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmenuRegistroValoresActionPerformed
        // TODO add your handling code here:
        RegistroValores frm = new RegistroValores();
        frm.lblEstadoValores.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
        this.dispose();
    }//GEN-LAST:event_JmenuRegistroValoresActionPerformed

    private void JmenuIngresoCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmenuIngresoCarrerasActionPerformed
        // TODO add your handling code here:

        IngresoCarreras frm = new IngresoCarreras();
        frm.lblEstadoCarrera.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
    }//GEN-LAST:event_JmenuIngresoCarrerasActionPerformed

    public static boolean TstVentHistorialCarrera=false;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalOperadoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalOperadoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalOperadoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalOperadoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalOperadoras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuChoferes;
    private javax.swing.JMenu JmenuCarreras;
    private javax.swing.JMenuItem JmenuIngresoCarreras;
    private javax.swing.JMenuItem JmenuPagosDiarios;
    private javax.swing.JMenuItem JmenuRegistroValores;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHistorialCarrera;
    private javax.swing.JMenuItem jMenuRegistro;
    private javax.swing.JMenuItem jMenuReportesChoferes;
    private javax.swing.JMenu jMenuSalir;
    public static javax.swing.JLabel lblCedulaUsuario;
    private javax.swing.JLabel lblClock;
    public static javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFondoFrame;
    private javax.swing.JLabel lblMenuPrincipal;
    private javax.swing.JLabel lblimagen;
    // End of variables declaration//GEN-END:variables
}
