/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import BO.PromocionesBo;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import proyecto_fastcar.Control;

/**
 *
 * @author Cardozo Villon
 */
public class MenuPrincipalConsulta extends javax.swing.JFrame implements ActionListener{
Timer timer = new Timer(1000, (ActionListener) this);
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipalConsulta() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/IMAGENES/icono.png")).getImage());
        setTitle("MENU PRINCIPAL USUARIO CONSULTA");
        lblEstado.setVisible(false);
        lblCedulaUsuario.setVisible(false);
        timer.start();
        ImageIcon fastcar = new ImageIcon(getClass().getResource("/IMAGENES/iconoFastcar.png"));
        ImageIcon icon = new ImageIcon(fastcar.getImage().getScaledInstance(lblimagen.getWidth(), lblimagen.getHeight(), Image.SCALE_DEFAULT));
        lblimagen.setIcon(icon);
        
        fastcar = new ImageIcon(getClass().getResource("/IMAGENES/fondo.jpeg"));
        icon = new ImageIcon(fastcar.getImage().getScaledInstance(lblFondoFrame.getWidth(), lblFondoFrame.getHeight(), Image.SCALE_DEFAULT));
        lblFondoFrame.setIcon(icon);
        
        //lblEstado.setVisible(false);
        setDefaultCloseOperation(0);
    }
    
    public void actionPerformed(ActionEvent e) {
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");         
        lblClock.setText(sdf.format(new java.util.Date()));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenuPrincipal = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        lblimagen = new javax.swing.JLabel();
        lblFondoFrame = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblCedulaUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JmenuCarreras = new javax.swing.JMenu();
        jmenuPromociones = new javax.swing.JMenu();
        jMenuIniciarPromocion = new javax.swing.JMenuItem();
        jMenuFinalizarPromocion = new javax.swing.JMenuItem();
        jMenuReportesCarreas = new javax.swing.JMenuItem();
        JMenuChoferes = new javax.swing.JMenu();
        jMenuReporteschoferes = new javax.swing.JMenuItem();
        jMenuRegistroChofer = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblMenuPrincipal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMenuPrincipal.setText("SISTEMA FASTCAR - MENU PRINCIPAL");

        lblClock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        JmenuCarreras.setText("CARRERAS");

        jmenuPromociones.setText("PROMOCIONES");

        jMenuIniciarPromocion.setText("INICIAR PROMOCION");
        jMenuIniciarPromocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIniciarPromocionActionPerformed(evt);
            }
        });
        jmenuPromociones.add(jMenuIniciarPromocion);

        jMenuFinalizarPromocion.setText("FINALIZAR PROMOCION");
        jMenuFinalizarPromocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFinalizarPromocionActionPerformed(evt);
            }
        });
        jmenuPromociones.add(jMenuFinalizarPromocion);

        JmenuCarreras.add(jmenuPromociones);

        jMenuReportesCarreas.setText("REPORTES");
        jMenuReportesCarreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReportesCarreasActionPerformed(evt);
            }
        });
        JmenuCarreras.add(jMenuReportesCarreas);

        jMenuBar1.add(JmenuCarreras);

        JMenuChoferes.setText("CHOFERES");

        jMenuReporteschoferes.setText("REPORTES");
        jMenuReporteschoferes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReporteschoferesActionPerformed(evt);
            }
        });
        JMenuChoferes.add(jMenuReporteschoferes);

        jMenuRegistroChofer.setText("REGISTRO");
        jMenuRegistroChofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegistroChoferActionPerformed(evt);
            }
        });
        JMenuChoferes.add(jMenuRegistroChofer);

        jMenuBar1.add(JMenuChoferes);

        jMenuSalir.setText("SALIR");
        jMenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuSalirMousePressed(evt);
            }
        });
        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lblMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFondoFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(222, 222, 222)
                    .addComponent(lblCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(223, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(lblMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFondoFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addComponent(lblCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(143, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuIniciarPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIniciarPromocionActionPerformed
        // TODO add your handling code here:
        IngresarPromociones frm = new IngresarPromociones();
        frm.lblEstadoPromociones.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
        this.dispose();
    }//GEN-LAST:event_jMenuIniciarPromocionActionPerformed

    private void jMenuFinalizarPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFinalizarPromocionActionPerformed
        // TODO add your handling code here:
        try {
                int n=0;
                int finalizarPromocion=0;
                PromocionesBo bo = new PromocionesBo();
                n=bo.ValidarPromociones();
                if(n==1){
                    int codigo=JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea finalizar la promocion?", "Alerta de Confirmacion!", JOptionPane.YES_NO_OPTION);
                        if (codigo==JOptionPane.YES_OPTION){    
                            finalizarPromocion=bo.FinalizarPromociones();
                            if(finalizarPromocion>0){
                                JOptionPane.showMessageDialog(rootPane,"SE FINALIZO LA PROMOCION CORRECTAMENTE");
                                
                            }
                        }else if(codigo==JOptionPane.NO_OPTION){
                            JOptionPane.showMessageDialog(rootPane,"SE HA CANCELADO LA ACCION");
                        }
                }else{
                    JOptionPane.showMessageDialog(null, "NO HAY PROMOCION REGISTRADA", "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MenuPrincipalConsulta.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(MenuPrincipalConsulta.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuFinalizarPromocionActionPerformed

    private void jMenuReportesCarreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReportesCarreasActionPerformed
        // TODO add your handling code here:
        ReporteCarrerasPDF frm = new ReporteCarrerasPDF();
        frm.lblEstadoReporteC.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
        this.dispose();
    }//GEN-LAST:event_jMenuReportesCarreasActionPerformed

    private void jMenuSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalirMousePressed
        // TODO add your handling code here:
        new Control().cerrarApp();
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirMousePressed

    private void jMenuReporteschoferesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReporteschoferesActionPerformed
        // TODO add your handling code here:
        ReporteChoferesPDF frm = new ReporteChoferesPDF();
        frm.lblReportechofer.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
        this.dispose();
    }//GEN-LAST:event_jMenuReporteschoferesActionPerformed

    private void jMenuRegistroChoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegistroChoferActionPerformed
        // TODO add your handling code here:
        IngresoChoferes frm = new IngresoChoferes();
        frm.lblEstadoIngresoC.setText(lblEstado.getText());
        frm.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
        frm.show();
        this.dispose();
    }//GEN-LAST:event_jMenuRegistroChoferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuChoferes;
    private javax.swing.JMenu JmenuCarreras;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuFinalizarPromocion;
    private javax.swing.JMenuItem jMenuIniciarPromocion;
    private javax.swing.JMenuItem jMenuRegistroChofer;
    private javax.swing.JMenuItem jMenuReportesCarreas;
    private javax.swing.JMenuItem jMenuReporteschoferes;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JMenu jmenuPromociones;
    public static javax.swing.JLabel lblCedulaUsuario;
    private javax.swing.JLabel lblClock;
    public static javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFondoFrame;
    private javax.swing.JLabel lblMenuPrincipal;
    private javax.swing.JLabel lblimagen;
    // End of variables declaration//GEN-END:variables
}
