/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import BO.ChoferesBo;
import BO.PagosDiariosBo;
import JB.Choferes;
import JB.PagosDiarios;
import java.awt.Image;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cardozo Villon
 */
public class PagosDiariosChoferes extends javax.swing.JFrame {

    /**
     * Creates new form PagosDiariosChoferes
     */
    public PagosDiariosChoferes() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/IMAGENES/icono.png")).getImage());
        setTitle("PAGOS DIARIOS CHOFERES");
        btnRegistrar.setEnabled(false);
        lblestadoPagos.setVisible(false);
        lblCedulaUsuario.setVisible(false);
        //txtPagosDiariosEstado.setVisible(false);
        
        ImageIcon fastcar = new ImageIcon(getClass().getResource("/IMAGENES/fondo.jpeg"));
        ImageIcon icon = new ImageIcon(fastcar.getImage().getScaledInstance(lblFondoFrame.getWidth(), lblFondoFrame.getHeight(), Image.SCALE_DEFAULT));
        lblFondoFrame.setIcon(icon);
        setDefaultCloseOperation(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIngresoChoferes = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblestadoPagos = new javax.swing.JLabel();
        lblCedulaUsuario = new javax.swing.JLabel();
        lblMovil = new javax.swing.JLabel();
        txtMovil = new javax.swing.JTextField();
        lblMovil1 = new javax.swing.JLabel();
        txtNombreChofer = new javax.swing.JTextField();
        txtModeloVehiculo = new javax.swing.JTextField();
        lblMovil2 = new javax.swing.JLabel();
        lblMovil3 = new javax.swing.JLabel();
        txtColorVehiculo = new javax.swing.JTextField();
        lblMovil4 = new javax.swing.JLabel();
        txtPlacaVehiculo = new javax.swing.JTextField();
        lblMovil5 = new javax.swing.JLabel();
        lblMovil6 = new javax.swing.JLabel();
        jDateFecha = new com.toedter.calendar.JDateChooser();
        txtValor = new javax.swing.JTextField();
        lblObservacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        lblFondoFrame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblIngresoChoferes.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblIngresoChoferes.setForeground(new java.awt.Color(255, 255, 255));
        lblIngresoChoferes.setText("SISTEMA FASTCAR - PAGOS DIARIOS");

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblMovil.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblMovil.setForeground(new java.awt.Color(255, 255, 255));
        lblMovil.setText("MOVIL");

        txtMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovilActionPerformed(evt);
            }
        });
        txtMovil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMovilKeyTyped(evt);
            }
        });

        lblMovil1.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblMovil1.setForeground(new java.awt.Color(255, 255, 255));
        lblMovil1.setText("NOMBRE CHOFER");

        txtNombreChofer.setEditable(false);

        txtModeloVehiculo.setEditable(false);

        lblMovil2.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblMovil2.setForeground(new java.awt.Color(255, 255, 255));
        lblMovil2.setText("MODELO");

        lblMovil3.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblMovil3.setForeground(new java.awt.Color(255, 255, 255));
        lblMovil3.setText("FECHA");

        txtColorVehiculo.setEditable(false);

        lblMovil4.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblMovil4.setForeground(new java.awt.Color(255, 255, 255));
        lblMovil4.setText("PLACA");

        txtPlacaVehiculo.setEditable(false);

        lblMovil5.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblMovil5.setForeground(new java.awt.Color(255, 255, 255));
        lblMovil5.setText("COLOR");

        lblMovil6.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblMovil6.setForeground(new java.awt.Color(255, 255, 255));
        lblMovil6.setText("VALOR");

        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorKeyTyped(evt);
            }
        });

        lblObservacion.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblObservacion.setForeground(new java.awt.Color(255, 255, 255));
        lblObservacion.setText("OBSERVACION");

        txtObservacion.setColumns(20);
        txtObservacion.setRows(5);
        jScrollPane1.setViewportView(txtObservacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMovil1)
                                    .addComponent(lblMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMovil2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblMovil6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblMovil5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblMovil3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtColorVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(lblMovil4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPlacaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtModeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRegistrar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRegresar))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lblIngresoChoferes, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(lblestadoPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(219, 219, 219)
                    .addComponent(lblCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(484, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFondoFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblestadoPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(370, 370, 370))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblIngresoChoferes, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMovil))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMovil1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreChofer))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMovil2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtColorVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMovil4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPlacaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMovil5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMovil3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMovil6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblObservacion, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                .addGap(95, 95, 95))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRegistrar)
                                    .addComponent(btnRegresar))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(188, 188, 188)
                    .addComponent(lblCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(282, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(lblFondoFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMovilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMovilKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_txtMovilKeyTyped

    private void txtMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMovilActionPerformed
        try {
        ChoferesBo bo= new ChoferesBo();
            Vector v1 = bo.ObtenerDatosChoferes(Integer.parseInt(txtMovil.getText()));
            if(!v1.isEmpty()){
            for(int i=0;i<v1.size();i++){
                Choferes ch = (Choferes)v1.get(i);
                txtNombreChofer.setText(ch.getLV_NOMBRES()+" "+ch.getLV_APELLIDOS());
                txtModeloVehiculo.setText(ch.getLV_MODELO());
                txtColorVehiculo.setText(ch.getLV_COLOR_VEHICULO());
                txtPlacaVehiculo.setText(ch.getLV_PLACA());
                btnRegistrar.setEnabled(true);
            }
            }else{
                JOptionPane.showMessageDialog(null, "NO EXISTE EL MOVIL: "+txtMovil.getText(), "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
                txtNombreChofer.setText(null);
                txtModeloVehiculo.setText(null);
                txtColorVehiculo.setText(null);
                txtPlacaVehiculo.setText(null);
                btnRegistrar.setEnabled(false);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PagosDiariosChoferes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PagosDiariosChoferes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtMovilActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void txtValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')&&(car!='.')) evt.consume();
    }//GEN-LAST:event_txtValorKeyTyped

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
        if(jDateFecha.getDate()==null && txtValor.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "LOS CAMPOS FECHA Y VALOR SON OBLIGATORIOS", "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                int n=0;
                int ingresoPagosDiarios=0;
                int movil=Integer.parseInt(txtMovil.getText());
                String diaf=null;
                String horasystem=null;
                        String mesf=null;
                        String dia = Integer.toString(jDateFecha.getCalendar().get(Calendar.DAY_OF_MONTH));
                        String mes = Integer.toString(jDateFecha.getCalendar().get(Calendar.MONTH)+ 1);
                        String year = Integer.toString(jDateFecha.getCalendar().get(Calendar.YEAR));
                        if(dia.length()==1){
                                    diaf="0"+dia;
                                    
                                }else{
                                    diaf=dia;
                                }
                                if (mes.length()==1){
                                    mesf="0"+mes;
                                }else{
                                    
                                    mesf=mes;
                                }
                        String fecha = (diaf + "/" + mesf+ "/" + year);
                        Date myDate = new Date();
                        SimpleDateFormat mdyFormat = new SimpleDateFormat("HH:mm:ss");
                        horasystem = mdyFormat.format(myDate);
                float valorPagar=Float.parseFloat(txtValor.getText());
                PagosDiariosBo bo = new PagosDiariosBo();
                n=bo.ValidarPagoDiarios(fecha, movil);
                if(n==0){
                    String estado=null;
                    ChoferesBo bo2= new ChoferesBo();
                    estado=bo2.EstadoMovil(movil);
                    Vector v1 = bo.ValidarPagoDiarioChofer(movil, fecha);
                    if ((int)v1.get(0) == 1 || (int)v1.get(0) == 0 || estado.equals("A")){
                        PagosDiarios in= new PagosDiarios(movil,fecha+" "+horasystem,valorPagar,lblCedulaUsuario.getText(),txtObservacion.getText());
                        ingresoPagosDiarios=bo.RegistrarPagosDiarios(in);
                        if(ingresoPagosDiarios>0){
                            JOptionPane.showMessageDialog(rootPane,"PAGO REGISTRADO CORRECTAMENTE");
                            txtMovil.setText(null);
                            txtNombreChofer.setText(null);
                            jDateFecha.setDate(null);
                            txtValor.setText(null); 
                            txtModeloVehiculo.setText(null);
                            txtColorVehiculo.setText(null);
                            txtPlacaVehiculo.setText(null);
                            txtObservacion.setText(null);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "NO SE PUEDE REALIZAR EL PAGO DE LA FECHA "+fecha+" DEBIDO QUE EL ULTIMO PAGO TIENE REGISTRADO ES EL "+(String)v1.get(1), "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);                  
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "EL MOVIL "+movil+" YA TIENE REGISTRADO EL PAGO EN LA FECHA "+fecha, "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(IngresoChoferes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(IngresoChoferes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        if(lblestadoPagos.getText().equals("A")){
            MenuPrincipalAdmin me = new MenuPrincipalAdmin();
            me.lblEstado.setText(lblestadoPagos.getText());
            me.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
            me.setLocationRelativeTo(null);
            me.show();
            this.dispose();
        }else if (lblestadoPagos.getText().equals("O")) {
            MenuPrincipalOperadoras me = new MenuPrincipalOperadoras();
            me.lblEstado.setText(lblestadoPagos.getText());
            me.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
            me.setLocationRelativeTo(null);
            me.show();
            this.dispose();
        }
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagosDiariosChoferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagosDiariosChoferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagosDiariosChoferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagosDiariosChoferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagosDiariosChoferes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private com.toedter.calendar.JDateChooser jDateFecha;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblCedulaUsuario;
    private javax.swing.JLabel lblFondoFrame;
    private javax.swing.JLabel lblIngresoChoferes;
    private javax.swing.JLabel lblMovil;
    private javax.swing.JLabel lblMovil1;
    private javax.swing.JLabel lblMovil2;
    private javax.swing.JLabel lblMovil3;
    private javax.swing.JLabel lblMovil4;
    private javax.swing.JLabel lblMovil5;
    private javax.swing.JLabel lblMovil6;
    private javax.swing.JLabel lblObservacion;
    public static javax.swing.JLabel lblestadoPagos;
    private javax.swing.JTextField txtColorVehiculo;
    private javax.swing.JTextField txtModeloVehiculo;
    private javax.swing.JTextField txtMovil;
    private javax.swing.JTextField txtNombreChofer;
    private javax.swing.JTextArea txtObservacion;
    private javax.swing.JTextField txtPlacaVehiculo;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
