/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import BO.CarrerasBo;
import proyecto_fastcar.PDFCarreras;
import JB.Carreras;
import com.itextpdf.text.BadElementException;
import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import proyecto_fastcar.PDFCarrerasFechas;
import proyecto_fastcar.PDFCarrerasMovil;

/**
 *
 * @author jcardozo
 */
public class ReporteCarrerasPDF extends javax.swing.JFrame {

    /**
     * Creates new form ReporteCarrerasPDF
     */
    public ReporteCarrerasPDF() {
        initComponents();
        jRadioButtonMovil.setSelected(true);
        lbMovil.setVisible(true);
        txtMovil.setVisible(true);
        lbfechaInicio.setVisible(true);
        lbfechaFin.setVisible(true);
        jDateFechaInicio.setVisible(true);
        jDateFechaFin.setVisible(true);
        lbtelefono.setVisible(false);
        txtTelefono.setVisible(false);
        //txtReportesCarrerasEstado.setVisible(false);
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/IMAGENES/icono.png")).getImage());
        setTitle("REPORTES CARRERAS");
        lblEstadoReporteC.setVisible(false);
        lblCedulaUsuario.setVisible(false);
        setDefaultCloseOperation(0);
        ImageIcon fastcar = new ImageIcon(getClass().getResource("/IMAGENES/fondo.jpeg"));
        ImageIcon icon = new ImageIcon(fastcar.getImage().getScaledInstance(lblfondoPanelCliente.getWidth(), lblfondoPanelCliente.getHeight(), Image.SCALE_DEFAULT));
        lblfondoPanelCliente.setIcon(icon);
        
        fastcar = new ImageIcon(getClass().getResource("/IMAGENES/fondo.jpeg"));
        icon = new ImageIcon(fastcar.getImage().getScaledInstance(lblFondoFrame.getWidth(), lblFondoFrame.getHeight(), Image.SCALE_DEFAULT));
        lblFondoFrame.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupfiltro = new javax.swing.ButtonGroup();
        lblReporteCarreras = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblBusqueda = new javax.swing.JLabel();
        jRadioButtontelefono = new javax.swing.JRadioButton();
        jRadioButtonMovil = new javax.swing.JRadioButton();
        lbMovil = new javax.swing.JLabel();
        txtMovil = new javax.swing.JTextField();
        lbfechaInicio = new javax.swing.JLabel();
        jDateFechaInicio = new com.toedter.calendar.JDateChooser();
        lbfechaFin = new javax.swing.JLabel();
        jDateFechaFin = new com.toedter.calendar.JDateChooser();
        lbtelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnPDF = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblfondoPanelCliente = new javax.swing.JLabel();
        rtbFechas = new javax.swing.JRadioButton();
        lblFondoFrame = new javax.swing.JLabel();
        lblEstadoReporteC = new javax.swing.JLabel();
        lblCedulaUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(580, 210));
        setResizable(false);

        lblReporteCarreras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblReporteCarreras.setForeground(new java.awt.Color(255, 255, 255));
        lblReporteCarreras.setText("SISTEMA FASTCAR - REPORTES CARRERAS");

        lblBusqueda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        lblBusqueda.setText("Escoga la busqueda");

        buttonGroupfiltro.add(jRadioButtontelefono);
        jRadioButtontelefono.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtontelefono.setText("TELEFONO");
        jRadioButtontelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButtontelefonoMousePressed(evt);
            }
        });

        buttonGroupfiltro.add(jRadioButtonMovil);
        jRadioButtonMovil.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonMovil.setText("MOVIL");
        jRadioButtonMovil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButtonMovilMousePressed(evt);
            }
        });

        lbMovil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbMovil.setForeground(new java.awt.Color(255, 255, 255));
        lbMovil.setText("Ingrese el movil");

        txtMovil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMovilKeyTyped(evt);
            }
        });

        lbfechaInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbfechaInicio.setForeground(new java.awt.Color(255, 255, 255));
        lbfechaInicio.setText("fecha Inicio");

        lbfechaFin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbfechaFin.setForeground(new java.awt.Color(255, 255, 255));
        lbfechaFin.setText("fecha Fin");

        lbtelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtelefono.setForeground(new java.awt.Color(255, 255, 255));
        lbtelefono.setText("Ingrese Telefono");

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        btnPDF.setText("GENERAR PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        buttonGroupfiltro.add(rtbFechas);
        rtbFechas.setForeground(new java.awt.Color(255, 255, 255));
        rtbFechas.setText("FECHAS");
        rtbFechas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rtbFechasMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(810, 810, 810))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonMovil)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtontelefono)
                        .addGap(18, 18, 18)
                        .addComponent(rtbFechas)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbfechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbfechaFin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(lblfondoPanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 478, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtontelefono)
                    .addComponent(jRadioButtonMovil)
                    .addComponent(rtbFechas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbfechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbfechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(9, 9, 9)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jDateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblfondoPanelCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblEstadoReporteC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblReporteCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFondoFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(266, 266, 266)
                    .addComponent(lblCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(267, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReporteCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoReporteC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFondoFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(lblCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(131, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMovilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonMovilMousePressed
        lbMovil.setVisible(true);
        txtMovil.setVisible(true);
        lbfechaInicio.setVisible(true);
        lbfechaFin.setVisible(true);
        jDateFechaInicio.setVisible(true);
        jDateFechaFin.setVisible(true);
        lbtelefono.setVisible(false);
        txtTelefono.setVisible(false);
    }//GEN-LAST:event_jRadioButtonMovilMousePressed

    private void jRadioButtontelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtontelefonoMousePressed
        // TODO add your handling code here:
        lbMovil.setVisible(false);
        txtMovil.setVisible(false);
        lbfechaInicio.setVisible(true);
        lbfechaFin.setVisible(true);
        jDateFechaInicio.setVisible(true);
        jDateFechaFin.setVisible(true);
        lbtelefono.setVisible(true);
        txtTelefono.setVisible(true);
    }//GEN-LAST:event_jRadioButtontelefonoMousePressed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        // TODO add your handling code here:
          if (jRadioButtontelefono.isSelected()){
                if(txtTelefono.getText().isEmpty() && jDateFechaInicio.getDate()==null && jDateFechaFin.getDate()==null){
                    JOptionPane.showMessageDialog(null, "DEBE INGRESAR EL NUMERO DE TELEFONO, LA FECHA DE INICIO Y FECHA FIN", "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
                }else{
                    try {
                        String diafini=null;
                                   String mesfini=null;
                                   String diaini = Integer.toString(jDateFechaInicio.getCalendar().get(Calendar.DAY_OF_MONTH));
                                   String mesini = Integer.toString(jDateFechaInicio.getCalendar().get(Calendar.MONTH)+ 1);
                                   String yearini = Integer.toString(jDateFechaInicio.getCalendar().get(Calendar.YEAR));
                                   if(diaini.length()==1){
                                       diafini="0"+diaini; 
                                   }else{
                                       diafini=diaini;
                                   }
                                   if (mesini.length()==1){
                                       mesfini="0"+mesini;
                                   }else{
                                       
                                       mesfini=mesini;
                                   }
                                   
                                   String diaffin=null;
                                   String mesffin=null;
                                   String diafin = Integer.toString(jDateFechaFin.getCalendar().get(Calendar.DAY_OF_MONTH));
                                   String mesfin = Integer.toString(jDateFechaFin.getCalendar().get(Calendar.MONTH)+ 1);
                                   String yearfin = Integer.toString(jDateFechaFin.getCalendar().get(Calendar.YEAR));
                                   if(diafin.length()==1){
                                       diaffin="0"+diafin;
                                       
                                   }else{
                                       diaffin=diafin;
                                   }
                                   if (mesfin.length()==1){
                                       mesffin="0"+mesfin;
                                   }else{
                                       mesffin=mesfin;
                                   }
                                   String fechaini = (diafini + "/" + mesfini+ "/" + yearini);
                                   String fechafin = (diaffin + "/" + mesffin+ "/" + yearfin);
                        CarrerasBo bo= new CarrerasBo();
                        Vector v1 = bo.ObtenerHistorialCarrerasTelefono(txtTelefono.getText(),fechaini,fechafin);
                        if (v1.size()>0){
                            Date myDate = new Date();
                            SimpleDateFormat mdyFormat = new SimpleDateFormat("yyyymmdd_HHmmss");
                            String FechaHoraRegistro = mdyFormat.format(myDate);
                            
                            PDFCarreras pdf = new PDFCarreras();
                            String obtener_result=Boolean.toString(pdf.crearPDF("FastCart_"+FechaHoraRegistro+"_reporte_telefono.pdf", "REPORTE SISTEMA FAST-CAR", "Reporte de las carreras del telefono "+txtTelefono.getText()+" desde "+fechaini+" hasta "+fechafin,v1));
                            if (obtener_result.equals("true")){
                                JOptionPane.showMessageDialog(rootPane,"SE CREO CORRECTAMENTE EL ARCHIVO PDF EN LA RUTA C:\\pruebapdf\\"+"FastCar_"+FechaHoraRegistro+"_reporte_telefono.pdf");
                            txtTelefono.setText(null);
                            }
                        }else{
                            JOptionPane.showMessageDialog(null, "NO EXISTE INFORMACION PARA EL NUMERO TELEFONICO "+txtTelefono.getText(), "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(ReporteCarrerasPDF.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(ReporteCarrerasPDF.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (BadElementException ex) {
                        Logger.getLogger(ReporteCarrerasPDF.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(ReporteCarrerasPDF.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }else if (jRadioButtonMovil.isSelected()){
                if(txtMovil.getText().isEmpty()&& jDateFechaInicio.getDate()==null && jDateFechaFin.getDate()==null){
                    JOptionPane.showMessageDialog(null, "DEBE INGRESAR EL MOVIL, LA FECHA DE INICIO Y FECHA FIN", "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
                }else{
                    try {
                        String diafini=null;
                                   String mesfini=null;
                                   String diaini = Integer.toString(jDateFechaInicio.getCalendar().get(Calendar.DAY_OF_MONTH));
                                   String mesini = Integer.toString(jDateFechaInicio.getCalendar().get(Calendar.MONTH)+ 1);
                                   String yearini = Integer.toString(jDateFechaInicio.getCalendar().get(Calendar.YEAR));
                                   if(diaini.length()==1){
                                       diafini="0"+diaini; 
                                   }else{
                                       diafini=diaini;
                                   }
                                   if (mesini.length()==1){
                                       mesfini="0"+mesini;
                                   }else{
                                       
                                       mesfini=mesini;
                                   }
                                   
                                   String diaffin=null;
                                   String mesffin=null;
                                   String diafin = Integer.toString(jDateFechaFin.getCalendar().get(Calendar.DAY_OF_MONTH));
                                   String mesfin = Integer.toString(jDateFechaFin.getCalendar().get(Calendar.MONTH)+ 1);
                                   String yearfin = Integer.toString(jDateFechaFin.getCalendar().get(Calendar.YEAR));
                                   if(diafin.length()==1){
                                       diaffin="0"+diafin;
                                       
                                   }else{
                                       diaffin=diafin;
                                   }
                                   if (mesfin.length()==1){
                                       mesffin="0"+mesfin;
                                   }else{
                                       mesffin=mesfin;
                                   }
                                   String fechaini = (diafini + "/" + mesfini+ "/" + yearini);
                                   String fechafin = (diaffin + "/" + mesffin+ "/" + yearfin);
                        CarrerasBo bo= new CarrerasBo();
                        Vector v1 = bo.ObtenerHistorialCarrerasMovil(Integer.parseInt(txtMovil.getText()),fechaini,fechafin);
                        if (v1.size()>0){
                            Date myDate = new Date();
                            SimpleDateFormat mdyFormat = new SimpleDateFormat("yyyymmdd_HHmmss");
                            String FechaHoraRegistro = mdyFormat.format(myDate);
                            
                            PDFCarrerasMovil pdf = new PDFCarrerasMovil();
                            String obtener_result=Boolean.toString(pdf.crearPDF("FastCart_"+FechaHoraRegistro+"_reporte_movil.pdf", "REPORTE SISTEMA FAST-CAR", "Reporte de las carreras del movil "+txtMovil.getText()+" desde "+fechaini+" hasta "+fechafin,v1));
                            if (obtener_result.equals("true")){
                                JOptionPane.showMessageDialog(rootPane,"SE CREO CORRECTAMENTE EL ARCHIVO PDF EN LA RUTA C:\\pruebapdf\\"+"FastCar_"+FechaHoraRegistro+"_reporte_movil.pdf");
                            txtMovil.setText(null);
                            }
                        }else{
                            JOptionPane.showMessageDialog(null, "NO EXISTE INFORMACION PARA EL NUMERO MOVIL "+txtMovil.getText(), "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(ReporteCarrerasPDF.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(ReporteCarrerasPDF.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (BadElementException ex) {
                        Logger.getLogger(ReporteCarrerasPDF.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(ReporteCarrerasPDF.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }else if (rtbFechas.isSelected()){
                if(jDateFechaInicio.getDate()==null && jDateFechaFin.getDate()==null){
                    JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR LA FECHA DE INICIO Y FECHA FIN", "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
                }else{
                    try {
                        String diafini=null;
                                   String mesfini=null;
                                   String diaini = Integer.toString(jDateFechaInicio.getCalendar().get(Calendar.DAY_OF_MONTH));
                                   String mesini = Integer.toString(jDateFechaInicio.getCalendar().get(Calendar.MONTH)+ 1);
                                   String yearini = Integer.toString(jDateFechaInicio.getCalendar().get(Calendar.YEAR));
                                   if(diaini.length()==1){
                                       diafini="0"+diaini; 
                                   }else{
                                       diafini=diaini;
                                   }
                                   if (mesini.length()==1){
                                       mesfini="0"+mesini;
                                   }else{
                                       
                                       mesfini=mesini;
                                   }
                                   
                                   String diaffin=null;
                                   String mesffin=null;
                                   String diafin = Integer.toString(jDateFechaFin.getCalendar().get(Calendar.DAY_OF_MONTH));
                                   String mesfin = Integer.toString(jDateFechaFin.getCalendar().get(Calendar.MONTH)+ 1);
                                   String yearfin = Integer.toString(jDateFechaFin.getCalendar().get(Calendar.YEAR));
                                   if(diafin.length()==1){
                                       diaffin="0"+diafin;
                                       
                                   }else{
                                       diaffin=diafin;
                                   }
                                   if (mesfin.length()==1){
                                       mesffin="0"+mesfin;
                                   }else{
                                       mesffin=mesfin;
                                   }
                                   String fechaini = (diafini + "/" + mesfini+ "/" + yearini);
                                   String fechafin = (diaffin + "/" + mesffin+ "/" + yearfin);
                        CarrerasBo bo= new CarrerasBo();
                        Vector v1 = bo.ObtenerHistorialCarrerasFechas(fechaini,fechafin);
                        if (v1.size()>0){
                            Date myDate = new Date();
                            SimpleDateFormat mdyFormat = new SimpleDateFormat("yyyymmdd_HHmmss");
                            String FechaHoraRegistro = mdyFormat.format(myDate);
                            
                            PDFCarrerasFechas pdf = new PDFCarrerasFechas();
                            String obtener_result=Boolean.toString(pdf.crearPDF("FastCart_"+FechaHoraRegistro+"_reporte_Fechas.pdf", "REPORTE SISTEMA FAST-CAR", "Reporte de las carreras desde "+fechaini+" hasta "+fechafin,v1));
                            if (obtener_result.equals("true")){
                                JOptionPane.showMessageDialog(rootPane,"SE CREO CORRECTAMENTE EL ARCHIVO PDF EN LA RUTA C:\\pruebapdf\\"+"FastCar_"+FechaHoraRegistro+"_reporte_Fechas.pdf");
                            txtMovil.setText(null);
                            }
                        }else{
                            JOptionPane.showMessageDialog(null, "NO EXISTE INFORMACION PARA LAS FECHAS "+fechaini+" - "+fechafin, "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(ReporteCarrerasPDF.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(ReporteCarrerasPDF.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (BadElementException ex) {
                        Logger.getLogger(ReporteCarrerasPDF.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(ReporteCarrerasPDF.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
    }//GEN-LAST:event_btnPDFActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        if(lblEstadoReporteC.getText().equals("A")){
            MenuPrincipalAdmin me = new MenuPrincipalAdmin();
            me.lblEstado.setText(lblEstadoReporteC.getText());
            me.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
            me.setLocationRelativeTo(null);
            me.show();
            this.dispose();
        }else if (lblEstadoReporteC.getText().equals("C")) {
            MenuPrincipalConsulta me = new MenuPrincipalConsulta();
            me.lblEstado.setText(lblEstadoReporteC.getText());
            me.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
            me.setLocationRelativeTo(null);
            me.show();
            this.dispose();
        }else if (lblEstadoReporteC.getText().equals("O")) {
            MenuPrincipalOperadoras me = new MenuPrincipalOperadoras();
            me.lblEstado.setText(lblEstadoReporteC.getText());
            me.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
            me.setLocationRelativeTo(null);
            me.show();
            this.dispose();
        }
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtMovilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMovilKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume(); 
    }//GEN-LAST:event_txtMovilKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume(); 
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void rtbFechasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rtbFechasMousePressed
        // TODO add your handling code here:
        lbMovil.setVisible(false);
        txtMovil.setVisible(false);
        lbfechaInicio.setVisible(true);
        lbfechaFin.setVisible(true);
        jDateFechaInicio.setVisible(true);
        jDateFechaFin.setVisible(true);
        lbtelefono.setVisible(false);
        txtTelefono.setVisible(false);
    }//GEN-LAST:event_rtbFechasMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteCarrerasPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteCarrerasPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteCarrerasPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteCarrerasPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteCarrerasPDF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnRegresar;
    private javax.swing.ButtonGroup buttonGroupfiltro;
    private com.toedter.calendar.JDateChooser jDateFechaFin;
    private com.toedter.calendar.JDateChooser jDateFechaInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonMovil;
    private javax.swing.JRadioButton jRadioButtontelefono;
    private javax.swing.JLabel lbMovil;
    private javax.swing.JLabel lbfechaFin;
    private javax.swing.JLabel lbfechaInicio;
    private javax.swing.JLabel lblBusqueda;
    public static javax.swing.JLabel lblCedulaUsuario;
    public static javax.swing.JLabel lblEstadoReporteC;
    private javax.swing.JLabel lblFondoFrame;
    private javax.swing.JLabel lblReporteCarreras;
    private javax.swing.JLabel lblfondoPanelCliente;
    private javax.swing.JLabel lbtelefono;
    private javax.swing.JRadioButton rtbFechas;
    private javax.swing.JTextField txtMovil;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
