/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import BO.CarrerasBo;
import BO.PagosDiariosBo;
import proyecto_fastcar.PDFCarreras;
import JB.Carreras;
import com.itextpdf.text.BadElementException;
import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import proyecto_fastcar.PDFChoferes;
import proyecto_fastcar.PDFChoferesFechas;

/**
 *
 * @author jcardozo
 */
public class ReporteChoferesPDF extends javax.swing.JFrame {

    /**
     * Creates new form ReporteCarrerasPDF
     */
    public ReporteChoferesPDF() {
        initComponents();
        //txtReportesCarrerasEstado.setVisible(false);
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/IMAGENES/icono.png")).getImage());
        setTitle("REPORTES CHOFERES");
        lblReportechofer.setVisible(false);
        lblCedulaUsuario.setVisible(false);
        setDefaultCloseOperation(0);
        ImageIcon fastcar = new ImageIcon(getClass().getResource("/IMAGENES/fondo.jpeg"));
        ImageIcon icon = new ImageIcon(fastcar.getImage().getScaledInstance(lblfondoPanelCliente.getWidth(), lblfondoPanelCliente.getHeight(), Image.SCALE_DEFAULT));
        lblfondoPanelCliente.setIcon(icon);
        
        fastcar = new ImageIcon(getClass().getResource("/IMAGENES/fondo.jpeg"));
        icon = new ImageIcon(fastcar.getImage().getScaledInstance(lblFondoFrame.getWidth(), lblFondoFrame.getHeight(), Image.SCALE_DEFAULT));
        lblFondoFrame.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupfiltro = new javax.swing.ButtonGroup();
        lblReporteCarreras = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbMovil = new javax.swing.JLabel();
        txtMovil = new javax.swing.JTextField();
        lbfechaInicio = new javax.swing.JLabel();
        jDateFechaInicio = new com.toedter.calendar.JDateChooser();
        lbfechaFin = new javax.swing.JLabel();
        jDateFechaFin = new com.toedter.calendar.JDateChooser();
        btnPDF = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblfondoPanelCliente = new javax.swing.JLabel();
        lblFondoFrame = new javax.swing.JLabel();
        lblReportechofer = new javax.swing.JLabel();
        lblCedulaUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblReporteCarreras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblReporteCarreras.setForeground(new java.awt.Color(255, 255, 255));
        lblReporteCarreras.setText("SISTEMA FASTCAR - REPORTES CHOFERES");

        lbMovil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbMovil.setForeground(new java.awt.Color(255, 255, 255));
        lbMovil.setText("Ingrese el movil");

        txtMovil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMovilKeyTyped(evt);
            }
        });

        lbfechaInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbfechaInicio.setForeground(new java.awt.Color(255, 255, 255));
        lbfechaInicio.setText("fecha Inicio");

        lbfechaFin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbfechaFin.setForeground(new java.awt.Color(255, 255, 255));
        lbfechaFin.setText("fecha Fin");

        btnPDF.setText("GENERAR PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(292, 292, 292))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbfechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbfechaFin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(lblfondoPanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbfechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbfechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblfondoPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblReportechofer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblReporteCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFondoFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(266, 266, 266)
                    .addComponent(lblCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(267, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReporteCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReportechofer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFondoFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(lblCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(88, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        // TODO add your handling code here:
        if (!txtMovil.getText().isEmpty() && jDateFechaInicio.getDate()!=null && jDateFechaFin.getDate()!=null){
                    try {
                        String diafini=null;
                                   String mesfini=null;
                                   String diaini = Integer.toString(jDateFechaInicio.getCalendar().get(Calendar.DAY_OF_MONTH));
                                   String mesini = Integer.toString(jDateFechaInicio.getCalendar().get(Calendar.MONTH)+ 1);
                                   String yearini = Integer.toString(jDateFechaInicio.getCalendar().get(Calendar.YEAR));
                                   if(diaini.length()==1){
                                       diafini="0"+diaini; 
                                   }else{
                                       diafini=diaini;
                                   }
                                   if (mesini.length()==1){
                                       mesfini="0"+mesini;
                                   }else{
                                       
                                       mesfini=mesini;
                                   }
                                   
                                   String diaffin=null;
                                   String mesffin=null;
                                   String diafin = Integer.toString(jDateFechaFin.getCalendar().get(Calendar.DAY_OF_MONTH));
                                   String mesfin = Integer.toString(jDateFechaFin.getCalendar().get(Calendar.MONTH)+ 1);
                                   String yearfin = Integer.toString(jDateFechaFin.getCalendar().get(Calendar.YEAR));
                                   if(diafin.length()==1){
                                       diaffin="0"+diafin;
                                       
                                   }else{
                                       diaffin=diafin;
                                   }
                                   if (mesfin.length()==1){
                                       mesffin="0"+mesfin;
                                   }else{
                                       mesffin=mesfin;
                                   }
                                   String fechaini = (diafini + "/" + mesfini+ "/" + yearini);
                                   String fechafin = (diaffin + "/" + mesffin+ "/" + yearfin);
                        CarrerasBo bo= new CarrerasBo();
                        Vector v1 = bo.ObtenerHistorialChoferesMovil(Integer.parseInt(txtMovil.getText()),fechaini,fechafin);
                        if (v1.size()>0){
                            Date myDate = new Date();
                            SimpleDateFormat mdyFormat = new SimpleDateFormat("yyyymmdd_HHmmss");
                            String FechaHoraRegistro = mdyFormat.format(myDate);
                            
                            PDFChoferes pdf = new PDFChoferes();
                            String obtener_result=Boolean.toString(pdf.crearPDF("FastCart_"+FechaHoraRegistro+"_reporte_pagos_"+txtMovil.getText()+".pdf", "REPORTE SISTEMA FAST-CAR", "Reporte de los pagos del movil "+txtMovil.getText()+" desde "+fechaini+" hasta "+fechafin,v1));
                            if (obtener_result.equals("true")){
                                JOptionPane.showMessageDialog(rootPane,"SE CREO CORRECTAMENTE EL ARCHIVO PDF EN LA RUTA C:\\pruebapdf\\"+"FastCar_"+FechaHoraRegistro+"_reporte_pagos_"+txtMovil.getText()+".pdf");
                            txtMovil.setText(null);
                            }
                        }else{
                            JOptionPane.showMessageDialog(null, "NO EXISTE INFORMACION PARA EL MOVIL "+txtMovil.getText(), "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(ReporteChoferesPDF.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(ReporteChoferesPDF.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (BadElementException ex) {
                        Logger.getLogger(ReporteChoferesPDF.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(ReporteChoferesPDF.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }  
        else if(jDateFechaInicio.getDate()!=null && jDateFechaFin.getDate()!=null){
                    try {
                                   String diafini=null;
                                   String mesfini=null;
                                   String diaini = Integer.toString(jDateFechaInicio.getCalendar().get(Calendar.DAY_OF_MONTH));
                                   String mesini = Integer.toString(jDateFechaInicio.getCalendar().get(Calendar.MONTH)+ 1);
                                   String yearini = Integer.toString(jDateFechaInicio.getCalendar().get(Calendar.YEAR));
                                   if(diaini.length()==1){
                                       diafini="0"+diaini; 
                                   }else{
                                       diafini=diaini;
                                   }
                                   if (mesini.length()==1){
                                       mesfini="0"+mesini;
                                   }else{
                                       
                                       mesfini=mesini;
                                   }
                                   
                                   String diaffin=null;
                                   String mesffin=null;
                                   String diafin = Integer.toString(jDateFechaFin.getCalendar().get(Calendar.DAY_OF_MONTH));
                                   String mesfin = Integer.toString(jDateFechaFin.getCalendar().get(Calendar.MONTH)+ 1);
                                   String yearfin = Integer.toString(jDateFechaFin.getCalendar().get(Calendar.YEAR));
                                   if(diafin.length()==1){
                                       diaffin="0"+diafin;
                                       
                                   }else{
                                       diaffin=diafin;
                                   }
                                   if (mesfin.length()==1){
                                       mesffin="0"+mesfin;
                                   }else{
                                       mesffin=mesfin;
                                   }
                                   String fechaini = (diafini + "/" + mesfini+ "/" + yearini);
                                   String fechafin = (diaffin + "/" + mesffin+ "/" + yearfin);
                        PagosDiariosBo bo= new PagosDiariosBo();
                        Vector v1 = bo.ObtenerPaosDiariosFechas(fechaini,fechafin);
                        if (v1.size()>0){
                            Date myDate = new Date();
                            SimpleDateFormat mdyFormat = new SimpleDateFormat("yyyymmdd_HHmmss");
                            String FechaHoraRegistro = mdyFormat.format(myDate);
                            
                            PDFChoferesFechas pdf = new PDFChoferesFechas();
                            String obtener_result=Boolean.toString(pdf.crearPDF("FastCart_"+FechaHoraRegistro+"_reporte_pagos_fechas.pdf", "REPORTE SISTEMA FAST-CAR", "Reporte de los pagos desde "+fechaini+" hasta "+fechafin,v1));
                            if (obtener_result.equals("true")){
                                JOptionPane.showMessageDialog(rootPane,"SE CREO CORRECTAMENTE EL ARCHIVO PDF EN LA RUTA C:\\pruebapdf\\"+"FastCar_"+FechaHoraRegistro+"_reporte_pagos_"+txtMovil.getText()+".pdf");
                            txtMovil.setText(null);
                            }
                        }else{
                            JOptionPane.showMessageDialog(null, "NO EXISTE INFORMACION PARA LAS FECHAS DESDE "+fechaini+" HASTA "+fechafin, "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(ReporteChoferesPDF.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(ReporteChoferesPDF.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (BadElementException ex) {
                        Logger.getLogger(ReporteChoferesPDF.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(ReporteChoferesPDF.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "DEBE INGRESAR LOS 3 CAMPOS O SOLO LAS DOS FECHAS", "MENSAJE ALERTA", JOptionPane.ERROR_MESSAGE);
                }
    }//GEN-LAST:event_btnPDFActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        if(lblReportechofer.getText().equals("A")){
            MenuPrincipalAdmin me = new MenuPrincipalAdmin();
            me.lblEstado.setText(lblReportechofer.getText());
            me.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
            me.setLocationRelativeTo(null);
            me.show();
            this.dispose();
        }else if (lblReportechofer.getText().equals("C")) {
            MenuPrincipalConsulta me = new MenuPrincipalConsulta();
            me.lblEstado.setText(lblReportechofer.getText());
            me.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
            me.setLocationRelativeTo(null);
            me.show();
            this.dispose();
        }else if (lblReportechofer.getText().equals("O")) {
            MenuPrincipalOperadoras me = new MenuPrincipalOperadoras();
            me.lblEstado.setText(lblReportechofer.getText());
            me.lblCedulaUsuario.setText(this.lblCedulaUsuario.getText());
            me.setLocationRelativeTo(null);
            me.show();
            this.dispose();
        }
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtMovilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMovilKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume(); 
    }//GEN-LAST:event_txtMovilKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteChoferesPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteChoferesPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteChoferesPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteChoferesPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteChoferesPDF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnRegresar;
    private javax.swing.ButtonGroup buttonGroupfiltro;
    private com.toedter.calendar.JDateChooser jDateFechaFin;
    private com.toedter.calendar.JDateChooser jDateFechaInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMovil;
    private javax.swing.JLabel lbfechaFin;
    private javax.swing.JLabel lbfechaInicio;
    public static javax.swing.JLabel lblCedulaUsuario;
    private javax.swing.JLabel lblFondoFrame;
    private javax.swing.JLabel lblReporteCarreras;
    public static javax.swing.JLabel lblReportechofer;
    private javax.swing.JLabel lblfondoPanelCliente;
    private javax.swing.JTextField txtMovil;
    // End of variables declaration//GEN-END:variables
}
